# Basic Site Settings
title: ""
email: "sarveshdhond@outlook.com"
description: "Data Analyst & Business Operations Expert"
url: "https://sarveshdhond.github.io"  # Replace with your actual GitHub Pages URL
baseurl: ""  # Leave empty for username.github.io

# Author Details
author: 
  name: ""
  title: "Data Analyst & Business Operations Expert"
  email: "sarveshdhond@outlook.com"
  location: "Toronto, ON"
  linkedin: "https://linkedin.com/in/sd1997"
  github: "https://github.com/SarveshDhond"
  twitter: "https://twitter.com/yourhandle"  # Optional, remove if not using Twitter
  personal_website: "https://sarveshdhond.com"  # Optional, remove if not using a personal website

# Resume Information
resume:
  # A brief profile/summary about you
  summary: |
    I am a data-driven professional with expertise in business operations, data analysis, and machine learning. I specialize in transforming complex datasets into actionable insights that drive business strategies. My experience spans across predictive modeling, SQL, Python programming, and visualizing data with Tableau and Power BI. I’m passionate about identifying trends and creating data-driven solutions that optimize decision-making processes.

  # Key Skills Section
  skills:
    - "Python (Pandas, Numpy, TensorFlow)"
    - "SQL (MySQL, PostgreSQL)"
    - "Data Visualization (Tableau, Power BI)"
    - "Machine Learning (Scikit-learn, XGBoost)"
    - "Predictive Analytics & Data Science"
    - "Business Intelligence & Reporting"
    - "Data Cleansing & Preprocessing"
    - "Excel (Advanced Functions, VBA)"
    - "Data Engineering (ETL processes)"

  # Education Section
  education:
    - institution: "Fanshawe College"
      degree: "Post-graduate Diploma in Marketing Management"
      duration: "Sept 2019 – Apr 2020"
      description: |
        Gained advanced knowledge of marketing strategies, consumer behavior, and market analysis. 
        Developed skills in digital marketing, data-driven decision making, and marketing analytics.

    - institution: "Fleming College"
      degree: "Post-graduate Diploma in Business Management"
      duration: "Jan 2019 – Aug 2019"
      description: |
        Focused on business strategy, operations management, and financial analysis. 
        Developed hands-on experience in project management, team leadership, and business performance optimization.

    - institution: "University of Mumbai"
      degree: "Bachelor’s Degree in Accounting"
      duration: "Jun 2015 – Jul 2018"
      description: |
        Built foundational knowledge in accounting principles, financial reporting, and auditing. 
        Gained skills in financial analysis and business operations, preparing for a career in business management.

  # Work Experience Section
  experience:
    - title: "Senior Operations Analyst"
      company: "Manulife"
      location: "Toronto, ON"
      start_date: "Feb 2024"
      end_date: "Sep 2025"
      description: |
        - Led data analysis initiatives in collaboration with the Data Science team to identify and assess risk patterns, improving prediction accuracy by 15%.
        - Designed and optimized SQL queries to extract, manipulate, and aggregate multiple datasets, speeding up business insight delivery by 20%.
        - Performed exploratory data analysis (EDA) on large datasets using Python (Pandas, Numpy) and created actionable dashboards using Tableau and Power BI for better decision-making.

    - title: "Data Analyst"
      company: "Cooperators Insurance"
      location: "Toronto, ON"
      start_date: "Jun 2023"
      end_date: "Feb 2024"
      description: |
        - Automated complex data cleaning tasks using Python and Excel macros, reducing backlog by 60%.
        - Aggregated and analyzed large datasets from multiple systems (AS400, SAP) using advanced SQL queries to uncover key business insights.
        - Created interactive Tableau dashboards for commercial insurance data analysis, enhancing the reporting capabilities for the leadership team.

    - title: "Insurance Advisor"
      company: "Cooperators Insurance"
      location: "Peterborough, ON"
      start_date: "Jun 2022"
      end_date: "Jun 2023"
      description: |
        - Provided tailored insurance solutions to clients based on a deep understanding of their financial goals.
        - Used Salesforce to track customer interactions and sales cycles, contributing to a 30% increase in referrals.
        - Collaborated with IT teams to assist in migrating legacy systems to Salesforce, improving the CRM workflow.

    - title: "Financial Service Representative"
      company: "Momentum Financial"
      location: "Peterborough, ON"
      start_date: "Jun 2021"
      end_date: "Jun 2022"
      description: |
        - Achieved customer satisfaction scores of 90%+ by providing exceptional customer service and resolving financial queries.
        - Conducted audits of loans, cheques, and cash-handling records, ensuring compliance with financial standards.
        - Managed key performance indicators (KPIs) and goals for store operations, utilizing Excel to track performance and generate reports.

  # Projects Section
  projects:
    - title: "Telco Customer Churn Analysis"
      description: |
        Analyzed historical telecom customer data to identify churn drivers like service quality, customer tenure, and plan type. 
        Built a TensorFlow model with an 80% accuracy rate in predicting customer churn, enabling proactive retention strategies.
        Visualized high-risk customer segments using Seaborn and Matplotlib, informing customer retention campaigns.
      technologies:
        - "Python"
        - "TensorFlow"
        - "Pandas"
        - "Numpy"
        - "Matplotlib"
        - "Seaborn"

    - title: "Credit Risk Prediction Model"
      description: |
        Built multiple machine learning models (Random Forest, XGBoost) on credit risk data to predict the likelihood of loan applicants defaulting. 
        Used feature engineering techniques such as encoding categorical variables and normalizing numerical data. 
        Achieved 77% accuracy with Random Forest and provided key insights into factors influencing credit risk.
      technologies:
        - "Python"
        - "Scikit-learn"
        - "Pandas"
        - "Numpy"
        - "Matplotlib"
        - "Seaborn"

    - title: "Toronto Collision Analysis"
      description: |
        Analyzed accident data from the Toronto Police Service to uncover high-risk zones and accident hotspots. 
        Produced severity scores for accident-prone areas, and identified vulnerable road users and peak accident times. 
        Presented findings through an interactive Tableau dashboard that was used by city planners for improved traffic safety.
      technologies:
        - "Python"
        - "SQL"
        - "Tableau"

    - title: "Retail Sales Forecasting Model"
      description: |
        Developed a time-series forecasting model to predict future retail sales using ARIMA and LSTM networks. 
        The model accurately predicted monthly sales trends and helped the retail team optimize inventory levels. 
        Visualized the forecasting results and performance metrics using Matplotlib.
      technologies:
        - "Python"
        - "Pandas"
        - "Numpy"
        - "Statsmodels"
        - "TensorFlow"
        - "Matplotlib"

    - title: "Employee Performance Prediction"
      description: |
        Created a machine learning model to predict employee performance and turnover based on historical data (performance reviews, tenure, etc.). 
        Utilized Random Forest and provided actionable insights into employee retention and performance management strategies.
      technologies:
        - "Python"
        - "Scikit-learn"
        - "Pandas"
        - "Numpy"
        - "Matplotlib"

# Social Media Links (Optional)
social_links:
  linkedin: "https://linkedin.com/in/sd1997"
  github: "https://github.com/SarveshDhond"
  twitter: "https://twitter.com/yourhandle"  # Optional, remove if not using Twitter
  email: "mailto:sarveshdhond@outlook.com"

# Exclude files/folders from the build process
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# SEO and Meta Tags Plugin (Optional)
plugins:
  - jekyll-seo-tag


# SEO and Meta Tags Plugin (Optional)
plugins:
  - jekyll-seo-tag
