# Basic Site Settings
title: "Sarvesh Dhond"
email: "sarveshdhond@outlook.com"
description: "Data Analyst & Business Operations Expert"
url: "https://sarveshdhond.github.io"  # Replace with your actual GitHub Pages URL
baseurl: ""  # Leave empty for username.github.io

# Author Details
author:
  name: "Sarvesh Dhond"
  title: "Data Analyst & Business Operations Expert"
  email: "sarveshdhond@outlook.com"
  location: "Toronto, ON"
  linkedin: "https://linkedin.com/in/sd1997"
  github: "https://github.com/SarveshDhond"
  twitter: "https://twitter.com/yourhandle"  # Optional, remove if not using Twitter
  personal_website: "https://sarveshdhond.com"  # Optional, remove if not using a personal website

# Resume Information
resume:
  # A brief profile/summary about you
  summary: |
    A skilled data analyst with extensive experience in business operations, data analysis, and machine learning. 
    Adept at transforming data into actionable insights to drive business strategy and enhance decision-making processes. 
    Strong expertise in SQL, Python, Tableau, Power BI, and predictive modeling to solve complex business problems.

  # Key Skills Section
  skills:
    - "Python"
    - "SQL"
    - "Tableau"
    - "Power BI"
    - "Excel"
    - "Machine Learning"
    - "Data Visualization"
    - "Business Intelligence"
    - "Predictive Analytics"
    - "Operations Management"
    - "Data Cleansing & Preprocessing"

  # Education Section
  education:
    - institution: "Fanshawe College"
      degree: "Post-graduate Diploma in Marketing Management"
      duration: "Sept 2019 – Apr 2020"
    - institution: "Fleming College"
      degree: "Post-graduate Diploma in Business Management"
      duration: "Jan 2019 – Aug 2019"
    - institution: "University of Mumbai"
      degree: "Bachelor’s Degree in Accounting"
      duration: "Jun 2015 – Jul 2018"

  # Work Experience Section
  experience:
    - title: "Senior Operations Analyst"
      company: "Manulife"
      location: "Toronto, ON"
      start_date: "Feb 2024"
      end_date: "Sep 2025"
      description: |
        - Collaborated with the Data Science team to clean and pre-process data, increasing prediction accuracy by 15%.
        - Designed complex SQL queries to extract and aggregate multiple datasets, improving the speed of delivering business insights.
        - Conducted exploratory data analysis using Pandas and Numpy, then presented findings in interactive Tableau and Power BI dashboards.

    - title: "Data Analyst"
      company: "Cooperators Insurance"
      location: "Toronto, ON"
      start_date: "Jun 2023"
      end_date: "Feb 2024"
      description: |
        - Automated data cleaning tasks with Python and Excel Macros, reducing the time spent on data preprocessing by 60%.
        - Aggregated data from AS400 and SAP systems using advanced SQL queries for deeper business insights.
        - Developed Tableau dashboards for visualizing commercial insurance data trends and business performance.

    - title: "Insurance Advisor"
      company: "Cooperators Insurance"
      location: "Peterborough, ON"
      start_date: "Jun 2022"
      end_date: "Jun 2023"
      description: |
        - Provided tailored insurance recommendations for clients based on their specific needs and goals.
        - Managed and tracked sales activities and customer referrals using Salesforce and Excel.
        - Assisted in the transition of legacy systems to Salesforce CRM to streamline customer interaction processes.

    - title: "Financial Service Representative"
      company: "Momentum Financial"
      location: "Peterborough, ON"
      start_date: "Jun 2021"
      end_date: "Jun 2022"
      description: |
        - Ensured customer satisfaction by maintaining a high service quality with a 90%+ satisfaction rate.
        - Conducted audits on loan records, cheques, and cash handling, ensuring compliance with financial regulations.
        - Monitored in-store KPIs and sales targets using Excel to drive performance and meet organizational goals.

  # Projects Section
  projects:
    - title: "Telco Customer Churn Analysis"
      description: |
        Analyzed customer data to identify churn drivers, such as service issues and customer demographics. 
        Developed a predictive model using TensorFlow, achieving 80% accuracy in forecasting churn risk.
        Created visualizations with Seaborn and Matplotlib to identify patterns and high-risk segments.
      technologies:
        - "Python"
        - "TensorFlow"
        - "Numpy"
        - "Seaborn"
        - "Matplotlib"

    - title: "Credit Risk Prediction Model"
      description: |
        Built multiple machine learning models (Random Forest, XGBoost, Decision Trees) on credit data to predict applicant risk. 
        Successfully identified key risk drivers and achieved 77% prediction accuracy using Random Forest. 
        Handled missing data, encoded categorical variables, and normalized numerical features to improve model performance.
      technologies:
        - "Python"
        - "Pandas"
        - "Numpy"
        - "Scikit-learn"
        - "Matplotlib"
        - "Seaborn"

    - title: "Toronto Collision Analysis"
      description: |
        Analyzed collision data from the Toronto Police Service to identify patterns and high-risk areas for accidents. 
        Produced severity scoring for accident zones, identifying peak accident hours and the most vulnerable road users.
        Findings were presented in a Tableau dashboard for better decision-making and risk mitigation.
      technologies:
        - "Python"
        - "SQL"
        - "Tableau"

    - title: "Retail Sales Forecasting Model"
      description: |
        Developed a time-series forecasting model for retail sales using ARIMA and LSTM networks. 
        The model predicted monthly sales with a high degree of accuracy and helped optimize inventory levels.
        Visualized the forecasting results with Matplotlib to present trends and accuracy assessments.
      technologies:
        - "Python"
        - "Pandas"
        - "Numpy"
        - "Statsmodels"
        - "TensorFlow"
        - "Matplotlib"

    - title: "Employee Performance Prediction"
      description: |
        Created a machine learning model to predict employee performance based on historical data, including reviews, tenure, and other KPIs. 
        Implemented a Random Forest Classifier to predict performance outcomes and provide insights into retention strategies.
      technologies:
        - "Python"
        - "Scikit-learn"
        - "Pandas"
        - "Numpy"
        - "Matplotlib"

# Social Media Links (Optional)
social_links:
  linkedin: "https://linkedin.com/in/sd1997"
  github: "https://github.com/SarveshDhond"
  twitter: "https://twitter.com/yourhandle"  # Optional, remove if not using Twitter
  email: "mailto:sarveshdhond@outlook.com"

# Exclude files/folders from the build process
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# SEO and Meta Tags Plugin (Optional)
plugins:
  - jekyll-seo-tag
