title: "Sarvesh Dhond | Data Analyst & Operations Specialist"
description: "Data-driven professional with 5+ years in Finance & Insurance | Skilled in Python, SQL, Tableau, and Power BI"
theme: jekyll-theme-cayman-dark
show_downloads: false
Enable plugins and include CSS
plugins:
jekyll-seo-tag
jekyll-feed
include:
assets/css/style.css
