title: "Sarvesh Dhond"
description: "Resume of Sarvesh Dhond - Data Analyst & Business Operations Expert"
url: "https://sarveshdhond.github.io"  # Replace with your actual GitHub Pages URL
baseurl: "" # Keep empty if deploying to username.github.io
theme: jekyll-theme-minimal

# Optional - your social links
social_links:
  github: SarveshDhond
  linkedin: sd1997
  email: sarveshdhond@outlook.com

# Exclude these from the site build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
